<a href="https://colab.research.google.com/github/HanJaeHui-GitHub/ESAA/blob/main/ESAA_YB_Week1_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
print(null_vector.nbytes)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
vector1 = np.arange(10,50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
vector1_desc = np.sort(vector1)[::-1]
print(vector1_desc)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
vector2 = np.arange(9)
matrix1 = vector2.reshape(3,3)
print(matrix1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
vector3 = np.array([1,2,0,0,4,0])
print(np.where(vector3 != 0))

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [10]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [11]:
np.random.random((3,3))

array([[0.90901976, 0.8943871 , 0.21135749],
       [0.72985406, 0.05365487, 0.85465224],
       [0.48766439, 0.42105897, 0.64498909]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [12]:
matrix2 = np.random.random((10,10))
print(matrix2.min(),matrix2.max())

0.0054302469042321055 0.9931552375533355


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [13]:
vector5 = np.random.random(30)
print(vector5.mean())

0.5414283894016729


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
array2d = np.ones((5, 5))
array2d[1:-1, 1:-1] = 0
print(array2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan

False

False

nan

True

True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [15]:
matrix3 = np.zeros((5,5))
for i in range(1,5):
  matrix3[i,i-1] = i
print(matrix3)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [16]:
matrix4 = np.zeros((8,8))
matrix4[1::2, ::2] = 1
matrix4[::2, 1::2] = 1
print(matrix4)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [17]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [18]:
matrix5 = np.random.random((5,5))
normalized_matrix = (matrix5 - matrix5.mean())/matrix5.var()
print('original matrix:\n', matrix5, '\n', 'noramlized_matrix:\n', normalized_matrix)

original matrix:
 [[0.67296487 0.4753773  0.02522582 0.58732692 0.37143018]
 [0.75800617 0.49164186 0.53815157 0.99141714 0.84491868]
 [0.92072874 0.93917245 0.95675511 0.9192     0.25642082]
 [0.56265949 0.46595458 0.31400519 0.84888004 0.21217913]
 [0.83883365 0.1109318  0.84002815 0.10517887 0.32491133]] 
 noramlized_matrix:
 [[ 1.11722182 -1.13364668 -6.26166043  0.14165558 -2.3177864 ]
 [ 2.08599111 -0.9483648  -0.41853782  4.74495086  3.07607682]
 [ 3.93968622  4.14979238  4.35008967  3.92227114 -3.62794442]
 [-0.13934963 -1.24098791 -2.97195762  3.12120371 -4.13193476]
 [ 3.00675773 -5.28531912  3.02036516 -5.35085509 -2.84771752]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [19]:
rgba_dtype = np.dtype([
    ('Red', np.ubyte),
    ('Green', np.ubyte),
    ('Blue', np.ubyte),
    ('Alpha', np.ubyte)
])
print("Custom RGBA dtype:", rgba_dtype)

Custom RGBA dtype: [('Red', 'u1'), ('Green', 'u1'), ('Blue', 'u1'), ('Alpha', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [20]:
A = np.random.random((5,3))
B = np.random.random((3,2))

print("matrix A : \n", A)
print("matrix B : \n", B)
print("A*B : \n", A@B)

matrix A : 
 [[0.00240859 0.90404662 0.79310227]
 [0.21672391 0.05062027 0.93814201]
 [0.58903506 0.2911308  0.39512361]
 [0.86320949 0.37712125 0.91364173]
 [0.20193319 0.30984775 0.52451221]]
matrix B : 
 [[0.69421702 0.02217841]
 [0.99717212 0.52539633]
 [0.03633961 0.56984381]]
A*B : 
 [[0.93198319 0.92698061]
 [0.23502226 0.56599671]
 [0.71358432 0.39118166]
 [1.0085109  0.73791581]
 [0.46821757 0.46616146]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [21]:
A = np.arange(10)
print(A)
A[(3<=A) & (A<=8)]*=-1
print(A)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [33]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

- Legal

    Z**Z

    2 << Z >> 2

    1j*Z

    Z/1/1

- Illegal:

    Z <- Z

    Z\<Z\>Z

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [39]:
np.array(0) / np.array(0)

<ipython-input-39-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [40]:
np.array(0) // np.array(0)

<ipython-input-40-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [41]:
np.array([np.nan]).astype(int).astype(float)

<ipython-input-41-ea171f4782f5>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [42]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[0 3 3 7 4 2 5 0 7 4]
[4 5 1 8 4 6 3 6 1 6]
[3 4 5]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [24]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-24-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [25]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [43]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [44]:
A = np.array([1,2,3])
B = np.array([4,5,6])

C = np.multiply(np.add(A,B),np.divide(np.negative(A),2))
print("The answer is:",C)
((A+B)*(-A/2)) == C

The answer is: [ -2.5  -7.  -13.5]


array([ True,  True,  True])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [45]:
A = np.array([3.5,4.8,10.4])

B = A - A%1
print(B)

C = A//1
print(C)

[ 3.  4. 10.]
[ 3.  4. 10.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [47]:
array31 = np.array(np.random.random(25)*4)
array31 = array31.reshape(5,5)
print(array31)

print(np.min(array31),np.max(array31))

[[2.28119569 0.84818597 2.89490578 0.91906588 0.7746567 ]
 [3.28213096 1.80092777 1.78510916 3.86076143 3.20975807]
 [3.9829251  1.07909567 3.70347652 2.85811836 1.60360744]
 [0.08111198 1.91653659 3.6601024  0.25131661 1.6770773 ]
 [3.98628531 1.77477954 0.2449654  3.07185351 1.274788  ]]
0.08111197811758109 3.9862853119645836


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [48]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.04528891 0.08551314 0.17874004 0.25249381 0.33755694 0.4891449
 0.52969976 0.67795811 0.68323461 0.7324121 ]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [51]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

check = np.allclose(A,B)
print("matrix A:\n", A)
print("matrix B:\n", B)
print(check)

matrix A:
 [1 0 1 1 0]
matrix B:
 [0 1 0 0 1]
False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [61]:
A = np.random.random((10,2))
X = A[:,0]
Y = A[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.08129398 0.82803659 0.93566724 1.05554649 0.90920855 0.95639766
 0.73277246 0.47197186 1.07014144 0.61715159]
[0.61478537 0.43494022 1.27814999 1.15320104 0.75292606 1.45052935
 0.90969548 0.52614763 0.56578445 1.56614538]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [63]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.17234051 0.13713575 0.93259546 0.69681816 0.06600017 0.75546305
 0.75387619 0.92302454 0.71152476 0.12427096]
[0.17234051 0.13713575 0.         0.69681816 0.06600017 0.75546305
 0.75387619 0.92302454 0.71152476 0.12427096]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [64]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(Z); print(v)

differences = np.abs(Z - v)
closest_index = differences.argmin()
closest_value = Z[closest_index]
print(closest_value)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
1.9880133839795588
2


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [68]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index,value)
print("\n")
for index in np.ndindex(Z.shape):
    print(index,Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [70]:
n = 4
p = 8
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),1)
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 0. 1.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [92]:
# column 1
Z = np.random.randint(0,10,(3,3))
Z=Z[Z[:, 0].argsort()]
print("sorted martix: \n", Z)

sorted martix: 
 [[0 5 2]
 [2 8 5]
 [8 9 7]]


In [93]:
# column 2
Z = np.random.randint(0,10,(3,3))
Z=Z[Z[:, 1].argsort()]
print("sorted martix: \n", Z)

sorted martix: 
 [[0 4 7]
 [0 5 9]
 [8 6 6]]


In [87]:
# column 3

In [94]:
Z = np.random.randint(0,10,(3,3))
Z=Z[Z[:,2].argsort()]
print("sorted martix: \n", Z)

sorted martix: 
 [[3 0 1]
 [1 6 4]
 [6 0 6]]
